host = "localhost"
port = 8001
db_url = "sqlite:///:memory:" # Use an ephemeral in-memory database

scheduling_loop_interval = 10
scheduler_class_name = "stochastic.py:WeightedByCoresAvailability"
[scheduler_parameter_overrides]
unavailable_discount_factor = 0.1


[[targets]]
# https://portal.hpc.hsu-hh.de/documentation/hsuper/partitions/
id = "hsuper-small"
host = "hsuper-login01.hsu-hh.de"
batch_system = "slurm"
queue = "small"
nodes = 569
cores_per_node = 72
max_time = "72:00:00"
max_nodes = 5
tags = ["x86", "slurm"]
[targets.module_map]
MPI = "openmpi"

# vvv========== WindHPC Project ==========vvv

[[targets]]
id = "windhpc-hsu-full"
host = "windhpc00.hsu-hh.de"
batch_system = "slurm"
queue = "full"
nodes = 4
cores_per_node = 48
max_time = "12:00:00"
source_scripts = ["/etc/profile"]
tags = ["x86", "windhpc", "slurm"]
[targets.module_map]
MPI = "mpi"


[[targets]]
id = "windhpc-hlrs"
host = "training.hlrs.de"
batch_system = "pbs"
queue = "windhpc"
nodes = 5
cores_per_node = 48
max_time = "24:00:00"
tags = ["x86", "windhpc", "pbs"]
[targets.module_map]
MPI = "mpi/openmpi"


[[targets]]
id = "windhpc-wwit"
host = "windpark.windhpc.de"
batch_system = "slurm"
nodes = 5
cores_per_node = 48
max_time = "1-00:00:00"
source_scripts = ["/etc/profile"]
tags = ["x86", "green", "windhpc", "slurm"]
[targets.module_map]
MPI = "mpi/openmpi"

# ^^^========== WindHPC Project ==========^^^

# vvv========== NHR Systems ==========vvv

[[targets]]
# https://docs.hpc.gwdg.de/how_to_use/compute_partitions/cpu_partitions/index.html
id = "emmy-standard96s"
host = "glogin.hpc.gwdg.de"
batch_system = "slurm"
queue = "standard96s"
nodes = 200
cores_per_node = 96
max_time = "2-00:00:00"
max_nodes = 256
tags = ["x86", "nhr", "slurm"]
[targets.module_map]
MPI = "gcc/14.2.0 openmpi/5.0.6" # Hierarchical module system


[[targets]]
# https://doc.nhr.fau.de/clusters/fritz/
id = "fritz-singlenode"
host = "fritz.nhr.fau.de"
batch_system = "slurm"
queue = "singlenode"
constraints = "hwperf"
nodes = 992
cores_per_node = 72
max_time = "1-00:00:00"
max_nodes = 1
source_scripts = ["/etc/profile"]
tags = ["x86", "nhr", "slurm"]
[targets.module_map]
MPI = "openmpi/5.0.8-gcc11.5.0"


[[targets]]
# https://doc.nhr.fau.de/clusters/fritz/
id = "fritz-multinode"
host = "fritz.nhr.fau.de"
batch_system = "slurm"
queue = "multinode"
constraints = "hwperf"
nodes = 992
cores_per_node = 72
max_time = "1-00:00:00"
max_nodes = 64
min_nodes = 2
source_scripts = ["/etc/profile"]
tags = ["x86", "nhr", "slurm"]
[targets.module_map]
MPI = "openmpi/5.0.8-gcc11.5.0"

# ^^^========== NHR Systems ==========^^^
